name: release-workflow

on:
  push:
    branches:
      - 'chore/release_workflow'

jobs:
  build:
    name: Bump version and publish package(s)

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        # pulls all commits (needed for lerna / semantic release to correctly version)
        fetch-depth: 0
    - name: Get tags and filter trigger tags
      run: |
        git fetch --depth=1 origin "+refs/tags/*:refs/tags/*"
        git fetch --prune --unshallow
        git tag -d `git tag | grep -E '^trigger-'`
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build packages
      run: yarn build
    - name: Run unit tests
      run: yarn test

    - name: Configure npm and git
      run: |
        echo "@superset-viz-plugins:registry=http://registry.npmjs.org/" > .npmrc
        echo "registry=http://registry.npmjs.org/" >> .npmrc
        echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        npm whoami
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote set-url origin "https://${GITHUB_TOKEN}@github.com/nielsen-oss/superset-viz-plugins.git" > /dev/null 2>&1
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump version and publish package(s)
      run: |
        git tag -d `git tag | grep -E '^trigger-'`
        yarn prerelease
        yarn ci:release-from-tag
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
